### ISSUE TITLE
Extract extra info from headers_sent

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-httphandlerrunner#1]
**headers_sent** allows you to define a file and a line that has undesirable output, otherwise it is impossible to identify and correct the error, there is not enough of this and it is difficult to debug, but the edit is very small, but gives many possibilities, I hope this edit will fall into the main branch, thanks!

https://www.php.net/manual/en/function.headers-sent.php

---

Originally posted by @undercloud at https://github.com/zendframework/zend-httphandlerrunner/pull/13

**Comment by weierophinney** [comment]
@undercloud It is a new feature, please target develop branch. Also it needs tests to be accepted.

---

Originally posted by @Xerkus at https://github.com/zendframework/zend-httphandlerrunner/pull/13#issuecomment-478370582

**Comment by boesing** [comment]
Oh, I actually liek this and want to add this to v2
