### ISSUE TITLE
Move `EmitterInterface` into another project

### ISSUE THREAD

**Issue by ericfortmeyer** [laminas/laminas-httphandlerrunner#51]
## RFC

| Q                   | A      |
| ------------------- | ------ |
| Proposed Version(s) | 3.0.0  |
| BC Break?           | Yes |

### Goal

Allow users to use implementations of `EmitterInterface` without requiring `laminas-httphandlerrunner` be installed. 

### Background,

- Library authors may want to provide different implementations of `EmitterInterface` for different use cases.
- Implementations of `EmitterInterface` could be created that do not require all of `laminas-httphandlerrunner`.

**Note:** There are several forks of `laminas-httphandlerrunner` (See [non-exhaustive list](#list-of-copies-of-emitterinterface)) some of which contain only a copy of `EmitterInterface`

### Considerations

Users will have to implement the interface from [PHP Contrib](https://github.com/php-contrib) instead of `[laminas/laminas-httphandlerrunner](https://github.com/laminas/laminas-httphandlerrunner/)`. Since the interface will not change, users will only need to `composer require  php-contrib/http-emitter` or `composer require laminas/http-emitter`, then update the use statements in their projects.

### Proposal(s)

I am proposing that `EmitterInterface` be moved either to PHP Contrib or to a separate project in `laminas`. 

#### List of Copies of EmitterInterface

- https://github.com/tomrf/http-emitter/blob/master/src/Interface/SapiEmitterInterface.php
- https://github.com/zaphyr-org/http-emitter/blob/master/src/Contracts/EmitterInterface.php
- https://github.com/iziphp/http-response-emitter/blob/main/src/EmitterInterface.php

**Comment by Ocramius** [comment]
I disagree: the emitter is possibly the most important functionality of this package, which doesn't drag in any more dependencies than what is necessary for it to work.

Implementing the interface from this package is very much the correct way forward, IMO.

**Comment by Ocramius** [comment]
Closing here meanwhile: the `EmitterInterface` is effectively the center of this package, and splitting this package further doesn't bring any advantage, as further splitting is just dilution, given there are no transitive dependencies dragged in from here.
